# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import field_pb2 as field__pb2


class FieldStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetField = channel.unary_unary(
        '/field.Field/GetField',
        request_serializer=field__pb2.FieldRequest.SerializeToString,
        response_deserializer=field__pb2.FieldReply.FromString,
        )


class FieldServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetField(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FieldServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetField': grpc.unary_unary_rpc_method_handler(
          servicer.GetField,
          request_deserializer=field__pb2.FieldRequest.FromString,
          response_serializer=field__pb2.FieldReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'field.Field', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
