// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/seniority.proto

package seniority

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SeniorityRequest struct {
	Slow                 bool     `protobuf:"varint,1,opt,name=slow,proto3" json:"slow,omitempty"`
	Unreliable           bool     `protobuf:"varint,2,opt,name=unreliable,proto3" json:"unreliable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeniorityRequest) Reset()         { *m = SeniorityRequest{} }
func (m *SeniorityRequest) String() string { return proto.CompactTextString(m) }
func (*SeniorityRequest) ProtoMessage()    {}
func (*SeniorityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8db015f1739c2b26, []int{0}
}

func (m *SeniorityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeniorityRequest.Unmarshal(m, b)
}
func (m *SeniorityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeniorityRequest.Marshal(b, m, deterministic)
}
func (m *SeniorityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeniorityRequest.Merge(m, src)
}
func (m *SeniorityRequest) XXX_Size() int {
	return xxx_messageInfo_SeniorityRequest.Size(m)
}
func (m *SeniorityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SeniorityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SeniorityRequest proto.InternalMessageInfo

func (m *SeniorityRequest) GetSlow() bool {
	if m != nil {
		return m.Slow
	}
	return false
}

func (m *SeniorityRequest) GetUnreliable() bool {
	if m != nil {
		return m.Unreliable
	}
	return false
}

type SeniorityReply struct {
	Seniority            string   `protobuf:"bytes,1,opt,name=seniority,proto3" json:"seniority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeniorityReply) Reset()         { *m = SeniorityReply{} }
func (m *SeniorityReply) String() string { return proto.CompactTextString(m) }
func (*SeniorityReply) ProtoMessage()    {}
func (*SeniorityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8db015f1739c2b26, []int{1}
}

func (m *SeniorityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeniorityReply.Unmarshal(m, b)
}
func (m *SeniorityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeniorityReply.Marshal(b, m, deterministic)
}
func (m *SeniorityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeniorityReply.Merge(m, src)
}
func (m *SeniorityReply) XXX_Size() int {
	return xxx_messageInfo_SeniorityReply.Size(m)
}
func (m *SeniorityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SeniorityReply.DiscardUnknown(m)
}

var xxx_messageInfo_SeniorityReply proto.InternalMessageInfo

func (m *SeniorityReply) GetSeniority() string {
	if m != nil {
		return m.Seniority
	}
	return ""
}

func init() {
	proto.RegisterType((*SeniorityRequest)(nil), "seniority.SeniorityRequest")
	proto.RegisterType((*SeniorityReply)(nil), "seniority.SeniorityReply")
}

func init() { proto.RegisterFile("proto/seniority.proto", fileDescriptor_8db015f1739c2b26) }

var fileDescriptor_8db015f1739c2b26 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0xcd, 0xcb, 0xcc, 0x2f, 0xca, 0x2c, 0xa9, 0xd4, 0x03, 0xf3, 0x85, 0x38,
	0xe1, 0x02, 0x4a, 0x6e, 0x5c, 0x02, 0xc1, 0x30, 0x4e, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89,
	0x90, 0x10, 0x17, 0x4b, 0x71, 0x4e, 0x7e, 0xb9, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x98,
	0x2d, 0x24, 0xc7, 0xc5, 0x55, 0x9a, 0x57, 0x94, 0x9a, 0x93, 0x99, 0x98, 0x94, 0x93, 0x2a, 0xc1,
	0x04, 0x96, 0x41, 0x12, 0x51, 0xd2, 0xe3, 0xe2, 0x43, 0x32, 0xa7, 0x20, 0xa7, 0x52, 0x48, 0x86,
	0x0b, 0x61, 0x0d, 0xd8, 0x28, 0xce, 0x20, 0x84, 0x80, 0x51, 0x28, 0x17, 0x27, 0x5c, 0xbd, 0x90,
	0x07, 0x17, 0x8f, 0x7b, 0x6a, 0x09, 0x82, 0x2f, 0xad, 0x87, 0x70, 0x31, 0xba, 0xeb, 0xa4, 0x24,
	0xb1, 0x4b, 0x16, 0xe4, 0x54, 0x2a, 0x31, 0x24, 0xb1, 0x81, 0x3d, 0x68, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xb5, 0x9b, 0xf2, 0xe5, 0xf9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SeniorityClient is the client API for Seniority service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SeniorityClient interface {
	GetSeniority(ctx context.Context, in *SeniorityRequest, opts ...grpc.CallOption) (*SeniorityReply, error)
}

type seniorityClient struct {
	cc *grpc.ClientConn
}

func NewSeniorityClient(cc *grpc.ClientConn) SeniorityClient {
	return &seniorityClient{cc}
}

func (c *seniorityClient) GetSeniority(ctx context.Context, in *SeniorityRequest, opts ...grpc.CallOption) (*SeniorityReply, error) {
	out := new(SeniorityReply)
	err := c.cc.Invoke(ctx, "/seniority.Seniority/GetSeniority", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeniorityServer is the server API for Seniority service.
type SeniorityServer interface {
	GetSeniority(context.Context, *SeniorityRequest) (*SeniorityReply, error)
}

// UnimplementedSeniorityServer can be embedded to have forward compatible implementations.
type UnimplementedSeniorityServer struct {
}

func (*UnimplementedSeniorityServer) GetSeniority(ctx context.Context, req *SeniorityRequest) (*SeniorityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeniority not implemented")
}

func RegisterSeniorityServer(s *grpc.Server, srv SeniorityServer) {
	s.RegisterService(&_Seniority_serviceDesc, srv)
}

func _Seniority_GetSeniority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeniorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeniorityServer).GetSeniority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seniority.Seniority/GetSeniority",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeniorityServer).GetSeniority(ctx, req.(*SeniorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Seniority_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seniority.Seniority",
	HandlerType: (*SeniorityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSeniority",
			Handler:    _Seniority_GetSeniority_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/seniority.proto",
}
