// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/field.proto

package field

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldRequest struct {
	Slow                 bool     `protobuf:"varint,1,opt,name=slow,proto3" json:"slow,omitempty"`
	Unreliable           bool     `protobuf:"varint,2,opt,name=unreliable,proto3" json:"unreliable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldRequest) Reset()         { *m = FieldRequest{} }
func (m *FieldRequest) String() string { return proto.CompactTextString(m) }
func (*FieldRequest) ProtoMessage()    {}
func (*FieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c7cff13685faa4, []int{0}
}

func (m *FieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldRequest.Unmarshal(m, b)
}
func (m *FieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldRequest.Marshal(b, m, deterministic)
}
func (m *FieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldRequest.Merge(m, src)
}
func (m *FieldRequest) XXX_Size() int {
	return xxx_messageInfo_FieldRequest.Size(m)
}
func (m *FieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FieldRequest proto.InternalMessageInfo

func (m *FieldRequest) GetSlow() bool {
	if m != nil {
		return m.Slow
	}
	return false
}

func (m *FieldRequest) GetUnreliable() bool {
	if m != nil {
		return m.Unreliable
	}
	return false
}

type FieldReply struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldReply) Reset()         { *m = FieldReply{} }
func (m *FieldReply) String() string { return proto.CompactTextString(m) }
func (*FieldReply) ProtoMessage()    {}
func (*FieldReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c7cff13685faa4, []int{1}
}

func (m *FieldReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldReply.Unmarshal(m, b)
}
func (m *FieldReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldReply.Marshal(b, m, deterministic)
}
func (m *FieldReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldReply.Merge(m, src)
}
func (m *FieldReply) XXX_Size() int {
	return xxx_messageInfo_FieldReply.Size(m)
}
func (m *FieldReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldReply.DiscardUnknown(m)
}

var xxx_messageInfo_FieldReply proto.InternalMessageInfo

func (m *FieldReply) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func init() {
	proto.RegisterType((*FieldRequest)(nil), "field.FieldRequest")
	proto.RegisterType((*FieldReply)(nil), "field.FieldReply")
}

func init() { proto.RegisterFile("proto/field.proto", fileDescriptor_b0c7cff13685faa4) }

var fileDescriptor_b0c7cff13685faa4 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcb, 0x4c, 0xcd, 0x49, 0xd1, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x1c, 0x25, 0x27,
	0x2e, 0x1e, 0x37, 0x10, 0x23, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x88, 0x8b, 0xa5,
	0x38, 0x27, 0xbf, 0x5c, 0x82, 0x51, 0x81, 0x51, 0x83, 0x23, 0x08, 0xcc, 0x16, 0x92, 0xe3, 0xe2,
	0x2a, 0xcd, 0x2b, 0x4a, 0xcd, 0xc9, 0x4c, 0x4c, 0xca, 0x49, 0x95, 0x60, 0x02, 0xcb, 0x20, 0x89,
	0x28, 0x29, 0x71, 0x71, 0x41, 0xcd, 0x28, 0xc8, 0xa9, 0x14, 0x12, 0xe1, 0x82, 0x18, 0x0d, 0x36,
	0x82, 0x33, 0x08, 0xc2, 0x31, 0xb2, 0xe5, 0x62, 0x05, 0xab, 0x11, 0x32, 0xe1, 0xe2, 0x70, 0x4f,
	0x2d, 0x81, 0xb0, 0x85, 0xf5, 0x20, 0x2e, 0x42, 0x76, 0x81, 0x94, 0x20, 0xaa, 0x60, 0x41, 0x4e,
	0xa5, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0xd1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x69,
	0x79, 0x4f, 0xc9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FieldClient is the client API for Field service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FieldClient interface {
	GetField(ctx context.Context, in *FieldRequest, opts ...grpc.CallOption) (*FieldReply, error)
}

type fieldClient struct {
	cc *grpc.ClientConn
}

func NewFieldClient(cc *grpc.ClientConn) FieldClient {
	return &fieldClient{cc}
}

func (c *fieldClient) GetField(ctx context.Context, in *FieldRequest, opts ...grpc.CallOption) (*FieldReply, error) {
	out := new(FieldReply)
	err := c.cc.Invoke(ctx, "/field.Field/GetField", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FieldServer is the server API for Field service.
type FieldServer interface {
	GetField(context.Context, *FieldRequest) (*FieldReply, error)
}

// UnimplementedFieldServer can be embedded to have forward compatible implementations.
type UnimplementedFieldServer struct {
}

func (*UnimplementedFieldServer) GetField(ctx context.Context, req *FieldRequest) (*FieldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetField not implemented")
}

func RegisterFieldServer(s *grpc.Server, srv FieldServer) {
	s.RegisterService(&_Field_serviceDesc, srv)
}

func _Field_GetField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FieldServer).GetField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/field.Field/GetField",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FieldServer).GetField(ctx, req.(*FieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Field_serviceDesc = grpc.ServiceDesc{
	ServiceName: "field.Field",
	HandlerType: (*FieldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetField",
			Handler:    _Field_GetField_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/field.proto",
}
